/*
 * generated by Xtext 2.18.0
 */
package org.xtext.casino.dsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class SystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.System");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCasinoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cDomAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDomDomainParserRuleCall_2_0 = (RuleCall)cDomAssignment_2.eContents().get(0);
		private final Assignment cArchAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cArchArchitectureParserRuleCall_3_0 = (RuleCall)cArchAssignment_3.eContents().get(0);
		private final Assignment cTechAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTechTechnologyParserRuleCall_4_0 = (RuleCall)cTechAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		////---------------------- System ------------------------------------------------
		//System:
		//	'Casino' '{'
		//	dom=Domain
		//	arch=Architecture
		//	tech=Technology
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Casino' '{' dom=Domain arch=Architecture tech=Technology '}'
		public Group getGroup() { return cGroup; }
		
		//'Casino'
		public Keyword getCasinoKeyword_0() { return cCasinoKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//dom=Domain
		public Assignment getDomAssignment_2() { return cDomAssignment_2; }
		
		//Domain
		public RuleCall getDomDomainParserRuleCall_2_0() { return cDomDomainParserRuleCall_2_0; }
		
		//arch=Architecture
		public Assignment getArchAssignment_3() { return cArchAssignment_3; }
		
		//Architecture
		public RuleCall getArchArchitectureParserRuleCall_3_0() { return cArchArchitectureParserRuleCall_3_0; }
		
		//tech=Technology
		public Assignment getTechAssignment_4() { return cTechAssignment_4; }
		
		//Technology
		public RuleCall getTechTechnologyParserRuleCall_4_0() { return cTechTechnologyParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class DomainElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.Domain");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDomainKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cElementsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cElementsAbstractElementParserRuleCall_2_0 = (RuleCall)cElementsAssignment_2.eContents().get(0);
		private final Assignment cModulesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cModulesModuleParserRuleCall_3_0 = (RuleCall)cModulesAssignment_3.eContents().get(0);
		private final Assignment cRelationsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cRelationsRelationDomParserRuleCall_4_0 = (RuleCall)cRelationsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//// --------------------- Domain ------------------------------------------------
		//Domain:
		//	'domain' '{'
		//	elements+=AbstractElement*
		//	modules+=Module+
		//	relations+=RelationDom+
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'domain' '{' elements+=AbstractElement* modules+=Module+ relations+=RelationDom+ '}'
		public Group getGroup() { return cGroup; }
		
		//'domain'
		public Keyword getDomainKeyword_0() { return cDomainKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//elements+=AbstractElement*
		public Assignment getElementsAssignment_2() { return cElementsAssignment_2; }
		
		//AbstractElement
		public RuleCall getElementsAbstractElementParserRuleCall_2_0() { return cElementsAbstractElementParserRuleCall_2_0; }
		
		//modules+=Module+
		public Assignment getModulesAssignment_3() { return cModulesAssignment_3; }
		
		//Module
		public RuleCall getModulesModuleParserRuleCall_3_0() { return cModulesModuleParserRuleCall_3_0; }
		
		//relations+=RelationDom+
		public Assignment getRelationsAssignment_4() { return cRelationsAssignment_4; }
		
		//RelationDom
		public RuleCall getRelationsRelationDomParserRuleCall_4_0() { return cRelationsRelationDomParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class AbstractElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.AbstractElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSpecialEntityParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cGeneralEntityParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cTypeParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//AbstractElement:
		//	SpecialEntity | GeneralEntity | Type;
		@Override public ParserRule getRule() { return rule; }
		
		//SpecialEntity | GeneralEntity | Type
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SpecialEntity
		public RuleCall getSpecialEntityParserRuleCall_0() { return cSpecialEntityParserRuleCall_0; }
		
		//GeneralEntity
		public RuleCall getGeneralEntityParserRuleCall_1() { return cGeneralEntityParserRuleCall_1; }
		
		//Type
		public RuleCall getTypeParserRuleCall_2() { return cTypeParserRuleCall_2; }
	}
	public class ModuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.Module");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cModuleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSubmodulesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSubmodulesSubmoduleParserRuleCall_3_0 = (RuleCall)cSubmodulesAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Module:
		//	'module' name=ID '{'
		//	submodules+=Submodule+
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'module' name=ID '{' submodules+=Submodule+ '}'
		public Group getGroup() { return cGroup; }
		
		//'module'
		public Keyword getModuleKeyword_0() { return cModuleKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//submodules+=Submodule+
		public Assignment getSubmodulesAssignment_3() { return cSubmodulesAssignment_3; }
		
		//Submodule
		public RuleCall getSubmodulesSubmoduleParserRuleCall_3_0() { return cSubmodulesSubmoduleParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class SubmoduleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.Submodule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSubmoduleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cOperationsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cOperationsOperationParserRuleCall_3_0 = (RuleCall)cOperationsAssignment_3.eContents().get(0);
		private final Assignment cEntitiesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cEntitiesEntityParserRuleCall_4_0 = (RuleCall)cEntitiesAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Submodule:
		//	'submodule' name=ID '{'
		//	operations+=Operation+
		//	entities+=Entity+
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'submodule' name=ID '{' operations+=Operation+ entities+=Entity+ '}'
		public Group getGroup() { return cGroup; }
		
		//'submodule'
		public Keyword getSubmoduleKeyword_0() { return cSubmoduleKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//operations+=Operation+
		public Assignment getOperationsAssignment_3() { return cOperationsAssignment_3; }
		
		//Operation
		public RuleCall getOperationsOperationParserRuleCall_3_0() { return cOperationsOperationParserRuleCall_3_0; }
		
		//entities+=Entity+
		public Assignment getEntitiesAssignment_4() { return cEntitiesAssignment_4; }
		
		//Entity
		public RuleCall getEntitiesEntityParserRuleCall_4_0() { return cEntitiesEntityParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EntityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.Entity");
		private final Assignment cTypeAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cTypeQualifiedNameCrossReference_0 = (CrossReference)cTypeAssignment.eContents().get(0);
		private final RuleCall cTypeQualifiedNameIDTerminalRuleCall_0_1 = (RuleCall)cTypeQualifiedNameCrossReference_0.eContents().get(1);
		
		//Entity:
		//	type=[QualifiedName];
		@Override public ParserRule getRule() { return rule; }
		
		//type=[QualifiedName]
		public Assignment getTypeAssignment() { return cTypeAssignment; }
		
		//[QualifiedName]
		public CrossReference getTypeQualifiedNameCrossReference_0() { return cTypeQualifiedNameCrossReference_0; }
		
		//ID
		public RuleCall getTypeQualifiedNameIDTerminalRuleCall_0_1() { return cTypeQualifiedNameIDTerminalRuleCall_0_1; }
	}
	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.QualifiedName");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//QualifiedName:
		//	name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class OperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.Operation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOpKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cSubOperationParserRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Keyword cOperates_onKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTargetAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTargetEntityParserRuleCall_5_0 = (RuleCall)cTargetAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Operation:
		//	'op' '{'
		//	'type:' SubOperation
		//	'operates_on:' target+=Entity
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'op' '{' 'type:' SubOperation 'operates_on:' target+=Entity '}'
		public Group getGroup() { return cGroup; }
		
		//'op'
		public Keyword getOpKeyword_0() { return cOpKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'type:'
		public Keyword getTypeKeyword_2() { return cTypeKeyword_2; }
		
		//SubOperation
		public RuleCall getSubOperationParserRuleCall_3() { return cSubOperationParserRuleCall_3; }
		
		//'operates_on:'
		public Keyword getOperates_onKeyword_4() { return cOperates_onKeyword_4; }
		
		//target+=Entity
		public Assignment getTargetAssignment_5() { return cTargetAssignment_5; }
		
		//Entity
		public RuleCall getTargetEntityParserRuleCall_5_0() { return cTargetEntityParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class SubOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.SubOperation");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cReadKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cCreateKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//SubOperation:
		//	'Read' | 'Create';
		@Override public ParserRule getRule() { return rule; }
		
		//'Read' | 'Create'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'Read'
		public Keyword getReadKeyword_0() { return cReadKeyword_0; }
		
		//'Create'
		public Keyword getCreateKeyword_1() { return cCreateKeyword_1; }
	}
	public class GeneralEntityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.GeneralEntity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGeneralEntityKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cQualifiedNameParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPropertiesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPropertiesPropertyParserRuleCall_3_0 = (RuleCall)cPropertiesAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//GeneralEntity:
		//	'generalEntity' QualifiedName '{'
		//	properties+=Property+
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'generalEntity' QualifiedName '{' properties+=Property+ '}'
		public Group getGroup() { return cGroup; }
		
		//'generalEntity'
		public Keyword getGeneralEntityKeyword_0() { return cGeneralEntityKeyword_0; }
		
		//QualifiedName
		public RuleCall getQualifiedNameParserRuleCall_1() { return cQualifiedNameParserRuleCall_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//properties+=Property+
		public Assignment getPropertiesAssignment_3() { return cPropertiesAssignment_3; }
		
		//Property
		public RuleCall getPropertiesPropertyParserRuleCall_3_0() { return cPropertiesPropertyParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class PropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.Property");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cTypeTypeCrossReference_2_0 = (CrossReference)cTypeAssignment_2.eContents().get(0);
		private final RuleCall cTypeTypeIDTerminalRuleCall_2_0_1 = (RuleCall)cTypeTypeCrossReference_2_0.eContents().get(1);
		
		//Property:
		//	name=ID ':' type=[Type];
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID ':' type=[Type]
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//type=[Type]
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//[Type]
		public CrossReference getTypeTypeCrossReference_2_0() { return cTypeTypeCrossReference_2_0; }
		
		//ID
		public RuleCall getTypeTypeIDTerminalRuleCall_2_0_1() { return cTypeTypeIDTerminalRuleCall_2_0_1; }
	}
	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.Type");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDataTypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Type:
		//	'dataType' name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//'dataType' name=ID
		public Group getGroup() { return cGroup; }
		
		//'dataType'
		public Keyword getDataTypeKeyword_0() { return cDataTypeKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class SpecialEntityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.SpecialEntity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSpecialEntityKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cQualifiedNameParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPropertiesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPropertiesPropertyParserRuleCall_3_0 = (RuleCall)cPropertiesAssignment_3.eContents().get(0);
		private final Assignment cTransactionsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTransactionsTransactionParserRuleCall_4_0 = (RuleCall)cTransactionsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//SpecialEntity:
		//	'specialEntity' QualifiedName '{'
		//	properties+=Property+
		//	transactions+=Transaction+
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'specialEntity' QualifiedName '{' properties+=Property+ transactions+=Transaction+ '}'
		public Group getGroup() { return cGroup; }
		
		//'specialEntity'
		public Keyword getSpecialEntityKeyword_0() { return cSpecialEntityKeyword_0; }
		
		//QualifiedName
		public RuleCall getQualifiedNameParserRuleCall_1() { return cQualifiedNameParserRuleCall_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//properties+=Property+
		public Assignment getPropertiesAssignment_3() { return cPropertiesAssignment_3; }
		
		//Property
		public RuleCall getPropertiesPropertyParserRuleCall_3_0() { return cPropertiesPropertyParserRuleCall_3_0; }
		
		//transactions+=Transaction+
		public Assignment getTransactionsAssignment_4() { return cTransactionsAssignment_4; }
		
		//Transaction
		public RuleCall getTransactionsTransactionParserRuleCall_4_0() { return cTransactionsTransactionParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class TransactionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.Transaction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTrxKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cSubTransactionParserRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Assignment cOperatesonAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cOperatesonOperatesonParserRuleCall_4_0 = (RuleCall)cOperatesonAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Transaction:
		//	'trx' '{'
		//	'type:' SubTransaction
		//	operateson+=Operateson+
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'trx' '{' 'type:' SubTransaction operateson+=Operateson+ '}'
		public Group getGroup() { return cGroup; }
		
		//'trx'
		public Keyword getTrxKeyword_0() { return cTrxKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'type:'
		public Keyword getTypeKeyword_2() { return cTypeKeyword_2; }
		
		//SubTransaction
		public RuleCall getSubTransactionParserRuleCall_3() { return cSubTransactionParserRuleCall_3; }
		
		//operateson+=Operateson+
		public Assignment getOperatesonAssignment_4() { return cOperatesonAssignment_4; }
		
		//Operateson
		public RuleCall getOperatesonOperatesonParserRuleCall_4_0() { return cOperatesonOperatesonParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class SubTransactionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.SubTransaction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cExchangeKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cSaleKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//SubTransaction:
		//	'exchange' | 'sale';
		@Override public ParserRule getRule() { return rule; }
		
		//'exchange' | 'sale'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'exchange'
		public Keyword getExchangeKeyword_0() { return cExchangeKeyword_0; }
		
		//'sale'
		public Keyword getSaleKeyword_1() { return cSaleKeyword_1; }
	}
	public class OperatesonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.Operateson");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOperates_onKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cTypeGeneralEntityCrossReference_1_0 = (CrossReference)cTypeAssignment_1.eContents().get(0);
		private final RuleCall cTypeGeneralEntityIDTerminalRuleCall_1_0_1 = (RuleCall)cTypeGeneralEntityCrossReference_1_0.eContents().get(1);
		
		//Operateson:
		//	'operates_on:' type=[GeneralEntity];
		@Override public ParserRule getRule() { return rule; }
		
		//'operates_on:' type=[GeneralEntity]
		public Group getGroup() { return cGroup; }
		
		//'operates_on:'
		public Keyword getOperates_onKeyword_0() { return cOperates_onKeyword_0; }
		
		//type=[GeneralEntity]
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//[GeneralEntity]
		public CrossReference getTypeGeneralEntityCrossReference_1_0() { return cTypeGeneralEntityCrossReference_1_0; }
		
		//ID
		public RuleCall getTypeGeneralEntityIDTerminalRuleCall_1_0_1() { return cTypeGeneralEntityIDTerminalRuleCall_1_0_1; }
	}
	public class RelationDomElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.RelationDom");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cCompositionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cSourceKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTypeAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cTypeGeneralEntityCrossReference_5_0 = (CrossReference)cTypeAssignment_5.eContents().get(0);
		private final RuleCall cTypeGeneralEntityIDTerminalRuleCall_5_0_1 = (RuleCall)cTypeGeneralEntityCrossReference_5_0.eContents().get(1);
		private final Keyword cTargetKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cTargetAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cTargetEntityParserRuleCall_7_0 = (RuleCall)cTargetAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//RelationDom:
		//	'rel' '{'
		//	'type:' 'Composition'
		//	'source:' type=[GeneralEntity]
		//	'target:' target+=Entity
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'rel' '{' 'type:' 'Composition' 'source:' type=[GeneralEntity] 'target:' target+=Entity '}'
		public Group getGroup() { return cGroup; }
		
		//'rel'
		public Keyword getRelKeyword_0() { return cRelKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'type:'
		public Keyword getTypeKeyword_2() { return cTypeKeyword_2; }
		
		//'Composition'
		public Keyword getCompositionKeyword_3() { return cCompositionKeyword_3; }
		
		//'source:'
		public Keyword getSourceKeyword_4() { return cSourceKeyword_4; }
		
		//type=[GeneralEntity]
		public Assignment getTypeAssignment_5() { return cTypeAssignment_5; }
		
		//[GeneralEntity]
		public CrossReference getTypeGeneralEntityCrossReference_5_0() { return cTypeGeneralEntityCrossReference_5_0; }
		
		//ID
		public RuleCall getTypeGeneralEntityIDTerminalRuleCall_5_0_1() { return cTypeGeneralEntityIDTerminalRuleCall_5_0_1; }
		
		//'target:'
		public Keyword getTargetKeyword_6() { return cTargetKeyword_6; }
		
		//target+=Entity
		public Assignment getTargetAssignment_7() { return cTargetAssignment_7; }
		
		//Entity
		public RuleCall getTargetEntityParserRuleCall_7_0() { return cTargetEntityParserRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class ArchitectureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.Architecture");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cArchKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cComponentesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cComponentesComponentParserRuleCall_2_0 = (RuleCall)cComponentesAssignment_2.eContents().get(0);
		private final Assignment cRelationArchAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRelationArchRelationArchParserRuleCall_3_0 = (RuleCall)cRelationArchAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//// --------------------- Architecture ----------------------------------------------
		//Architecture:
		//	'arch' '{'
		//	componentes+=Component+
		//	relationArch+=RelationArch+
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'arch' '{' componentes+=Component+ relationArch+=RelationArch+ '}'
		public Group getGroup() { return cGroup; }
		
		//'arch'
		public Keyword getArchKeyword_0() { return cArchKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//componentes+=Component+
		public Assignment getComponentesAssignment_2() { return cComponentesAssignment_2; }
		
		//Component
		public RuleCall getComponentesComponentParserRuleCall_2_0() { return cComponentesComponentParserRuleCall_2_0; }
		
		//relationArch+=RelationArch+
		public Assignment getRelationArchAssignment_3() { return cRelationArchAssignment_3; }
		
		//RelationArch
		public RuleCall getRelationArchRelationArchParserRuleCall_3_0() { return cRelationArchRelationArchParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ComponentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.Component");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cComponentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cComponentNameParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLayerAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLayerLayerParserRuleCall_3_0 = (RuleCall)cLayerAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Component:
		//	'component' ComponentName '{'
		//	layer+=Layer+
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'component' ComponentName '{' layer+=Layer+ '}'
		public Group getGroup() { return cGroup; }
		
		//'component'
		public Keyword getComponentKeyword_0() { return cComponentKeyword_0; }
		
		//ComponentName
		public RuleCall getComponentNameParserRuleCall_1() { return cComponentNameParserRuleCall_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//layer+=Layer+
		public Assignment getLayerAssignment_3() { return cLayerAssignment_3; }
		
		//Layer
		public RuleCall getLayerLayerParserRuleCall_3_0() { return cLayerLayerParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ComponentNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.ComponentName");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cBackKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFrontKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//ComponentName:
		//	'Back' | 'Front';
		@Override public ParserRule getRule() { return rule; }
		
		//'Back' | 'Front'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'Back'
		public Keyword getBackKeyword_0() { return cBackKeyword_0; }
		
		//'Front'
		public Keyword getFrontKeyword_1() { return cFrontKeyword_1; }
	}
	public class LayerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.Layer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLayerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameLayerNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLayerSegmentsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLayerSegmentsLayerSegmentParserRuleCall_3_0 = (RuleCall)cLayerSegmentsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Layer:
		//	'layer' name=LayerName '{'
		//	layerSegments+=LayerSegment*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'layer' name=LayerName '{' layerSegments+=LayerSegment* '}'
		public Group getGroup() { return cGroup; }
		
		//'layer'
		public Keyword getLayerKeyword_0() { return cLayerKeyword_0; }
		
		//name=LayerName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//LayerName
		public RuleCall getNameLayerNameParserRuleCall_1_0() { return cNameLayerNameParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//layerSegments+=LayerSegment*
		public Assignment getLayerSegmentsAssignment_3() { return cLayerSegmentsAssignment_3; }
		
		//LayerSegment
		public RuleCall getLayerSegmentsLayerSegmentParserRuleCall_3_0() { return cLayerSegmentsLayerSegmentParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class LayerNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.LayerName");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cJavaScriptKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cEjbKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cWarKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		
		//LayerName:
		//	'JavaScript' | 'Ejb' | 'War';
		@Override public ParserRule getRule() { return rule; }
		
		//'JavaScript' | 'Ejb' | 'War'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'JavaScript'
		public Keyword getJavaScriptKeyword_0() { return cJavaScriptKeyword_0; }
		
		//'Ejb'
		public Keyword getEjbKeyword_1() { return cEjbKeyword_1; }
		
		//'War'
		public Keyword getWarKeyword_2() { return cWarKeyword_2; }
	}
	public class LayerSegmentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.LayerSegment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLayerSegmentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameLayerSegmentNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cRelationsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cRelationsLayerSegmentRelationParserRuleCall_3_1_0 = (RuleCall)cRelationsAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		private final Assignment cSublayerSegmentsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cSublayerSegmentsSublayerSegmentParserRuleCall_4_0 = (RuleCall)cSublayerSegmentsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//LayerSegment:
		//	'layerSegment' name=LayerSegmentName '{' ('{' relations+=LayerSegmentRelation* '}')?
		//	sublayerSegments+=SublayerSegment*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'layerSegment' name=LayerSegmentName '{' ('{' relations+=LayerSegmentRelation* '}')? sublayerSegments+=SublayerSegment*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'layerSegment'
		public Keyword getLayerSegmentKeyword_0() { return cLayerSegmentKeyword_0; }
		
		//name=LayerSegmentName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//LayerSegmentName
		public RuleCall getNameLayerSegmentNameParserRuleCall_1_0() { return cNameLayerSegmentNameParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('{' relations+=LayerSegmentRelation* '}')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_0() { return cLeftCurlyBracketKeyword_3_0; }
		
		//relations+=LayerSegmentRelation*
		public Assignment getRelationsAssignment_3_1() { return cRelationsAssignment_3_1; }
		
		//LayerSegmentRelation
		public RuleCall getRelationsLayerSegmentRelationParserRuleCall_3_1_0() { return cRelationsLayerSegmentRelationParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_2() { return cRightCurlyBracketKeyword_3_2; }
		
		//sublayerSegments+=SublayerSegment*
		public Assignment getSublayerSegmentsAssignment_4() { return cSublayerSegmentsAssignment_4; }
		
		//SublayerSegment
		public RuleCall getSublayerSegmentsSublayerSegmentParserRuleCall_4_0() { return cSublayerSegmentsSublayerSegmentParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class LayerSegmentNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.LayerSegmentName");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cServicesKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cUiKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cStoreKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cRestEntityKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cPojoKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cFacadeKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		private final Keyword cDtoKeyword_6 = (Keyword)cAlternatives.eContents().get(6);
		private final Keyword cUtilKeyword_7 = (Keyword)cAlternatives.eContents().get(7);
		private final Keyword cContainersKeyword_8 = (Keyword)cAlternatives.eContents().get(8);
		
		//LayerSegmentName:
		//	'Services' | 'Ui' | 'Store' | 'RestEntity' | 'Pojo' | 'Facade' | 'Dto' | 'Util' | 'Containers';
		@Override public ParserRule getRule() { return rule; }
		
		//'Services' | 'Ui' | 'Store' | 'RestEntity' | 'Pojo' | 'Facade' | 'Dto' | 'Util' | 'Containers'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'Services'
		public Keyword getServicesKeyword_0() { return cServicesKeyword_0; }
		
		//'Ui'
		public Keyword getUiKeyword_1() { return cUiKeyword_1; }
		
		//'Store'
		public Keyword getStoreKeyword_2() { return cStoreKeyword_2; }
		
		//'RestEntity'
		public Keyword getRestEntityKeyword_3() { return cRestEntityKeyword_3; }
		
		//'Pojo'
		public Keyword getPojoKeyword_4() { return cPojoKeyword_4; }
		
		//'Facade'
		public Keyword getFacadeKeyword_5() { return cFacadeKeyword_5; }
		
		//'Dto'
		public Keyword getDtoKeyword_6() { return cDtoKeyword_6; }
		
		//'Util'
		public Keyword getUtilKeyword_7() { return cUtilKeyword_7; }
		
		//'Containers'
		public Keyword getContainersKeyword_8() { return cContainersKeyword_8; }
	}
	public class LayerSegmentRelationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.LayerSegmentRelation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAllowedToUseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cLayerSegmentNameParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//LayerSegmentRelation:
		//	'allowedToUse:' LayerSegmentName;
		@Override public ParserRule getRule() { return rule; }
		
		//'allowedToUse:' LayerSegmentName
		public Group getGroup() { return cGroup; }
		
		//'allowedToUse:'
		public Keyword getAllowedToUseKeyword_0() { return cAllowedToUseKeyword_0; }
		
		//LayerSegmentName
		public RuleCall getLayerSegmentNameParserRuleCall_1() { return cLayerSegmentNameParserRuleCall_1; }
	}
	public class SublayerSegmentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.SublayerSegment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSublayerSegmentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSublayerSegmentNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//SublayerSegment:
		//	'sublayerSegment' name=SublayerSegmentName;
		@Override public ParserRule getRule() { return rule; }
		
		//'sublayerSegment' name=SublayerSegmentName
		public Group getGroup() { return cGroup; }
		
		//'sublayerSegment'
		public Keyword getSublayerSegmentKeyword_0() { return cSublayerSegmentKeyword_0; }
		
		//name=SublayerSegmentName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//SublayerSegmentName
		public RuleCall getNameSublayerSegmentNameParserRuleCall_1_0() { return cNameSublayerSegmentNameParserRuleCall_1_0; }
	}
	public class SublayerSegmentNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.SublayerSegmentName");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cActionsKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cReducersKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//SublayerSegmentName:
		//	'Actions' | 'Reducers';
		@Override public ParserRule getRule() { return rule; }
		
		//'Actions' | 'Reducers'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'Actions'
		public Keyword getActionsKeyword_0() { return cActionsKeyword_0; }
		
		//'Reducers'
		public Keyword getReducersKeyword_1() { return cReducersKeyword_1; }
	}
	public class RelationArchElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.RelationArch");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRelationArchKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSourceKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final RuleCall cLayerNameParserRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cTargetKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final RuleCall cLayerNameParserRuleCall_7 = (RuleCall)cGroup.eContents().get(7);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//RelationArch:
		//	'relationArch' name=ID '{'
		//	'source:' LayerName ','
		//	'target:' LayerName
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'relationArch' name=ID '{' 'source:' LayerName ',' 'target:' LayerName '}'
		public Group getGroup() { return cGroup; }
		
		//'relationArch'
		public Keyword getRelationArchKeyword_0() { return cRelationArchKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'source:'
		public Keyword getSourceKeyword_3() { return cSourceKeyword_3; }
		
		//LayerName
		public RuleCall getLayerNameParserRuleCall_4() { return cLayerNameParserRuleCall_4; }
		
		//','
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }
		
		//'target:'
		public Keyword getTargetKeyword_6() { return cTargetKeyword_6; }
		
		//LayerName
		public RuleCall getLayerNameParserRuleCall_7() { return cLayerNameParserRuleCall_7; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class TechnologyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.Technology");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTechKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cJavaAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cJavaJavaAppParserRuleCall_2_0 = (RuleCall)cJavaAssignment_2.eContents().get(0);
		private final Assignment cReactAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cReactReactAppParserRuleCall_3_0 = (RuleCall)cReactAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//// --------------------- Technology ------------------------------------------------
		//Technology:
		//	'tech' '{'
		//	java=JavaApp
		//	react=ReactApp
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'tech' '{' java=JavaApp react=ReactApp '}'
		public Group getGroup() { return cGroup; }
		
		//'tech'
		public Keyword getTechKeyword_0() { return cTechKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//java=JavaApp
		public Assignment getJavaAssignment_2() { return cJavaAssignment_2; }
		
		//JavaApp
		public RuleCall getJavaJavaAppParserRuleCall_2_0() { return cJavaJavaAppParserRuleCall_2_0; }
		
		//react=ReactApp
		public Assignment getReactAssignment_3() { return cReactAssignment_3; }
		
		//ReactApp
		public RuleCall getReactReactAppParserRuleCall_3_0() { return cReactReactAppParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class JavaAppElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.JavaApp");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cJavaAppKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//// --------------------- Backend----- ----------------------------------------------
		//JavaApp:
		//	'javaApp' '{'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'javaApp' '{' '}'
		public Group getGroup() { return cGroup; }
		
		//'javaApp'
		public Keyword getJavaAppKeyword_0() { return cJavaAppKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2() { return cRightCurlyBracketKeyword_2; }
	}
	public class ReactAppElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.casino.dsl.Dsl.ReactApp");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cReactAppKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//// --------------------- Frontend---- ----------------------------------------------
		//ReactApp:
		//	'reactApp' '{'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'reactApp' '{' '}'
		public Group getGroup() { return cGroup; }
		
		//'reactApp'
		public Keyword getReactAppKeyword_0() { return cReactAppKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2() { return cRightCurlyBracketKeyword_2; }
	}
	
	
	private final SystemElements pSystem;
	private final DomainElements pDomain;
	private final AbstractElementElements pAbstractElement;
	private final ModuleElements pModule;
	private final SubmoduleElements pSubmodule;
	private final EntityElements pEntity;
	private final QualifiedNameElements pQualifiedName;
	private final OperationElements pOperation;
	private final SubOperationElements pSubOperation;
	private final GeneralEntityElements pGeneralEntity;
	private final PropertyElements pProperty;
	private final TypeElements pType;
	private final SpecialEntityElements pSpecialEntity;
	private final TransactionElements pTransaction;
	private final SubTransactionElements pSubTransaction;
	private final OperatesonElements pOperateson;
	private final RelationDomElements pRelationDom;
	private final ArchitectureElements pArchitecture;
	private final ComponentElements pComponent;
	private final ComponentNameElements pComponentName;
	private final LayerElements pLayer;
	private final LayerNameElements pLayerName;
	private final LayerSegmentElements pLayerSegment;
	private final LayerSegmentNameElements pLayerSegmentName;
	private final LayerSegmentRelationElements pLayerSegmentRelation;
	private final SublayerSegmentElements pSublayerSegment;
	private final SublayerSegmentNameElements pSublayerSegmentName;
	private final RelationArchElements pRelationArch;
	private final TechnologyElements pTechnology;
	private final JavaAppElements pJavaApp;
	private final ReactAppElements pReactApp;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pSystem = new SystemElements();
		this.pDomain = new DomainElements();
		this.pAbstractElement = new AbstractElementElements();
		this.pModule = new ModuleElements();
		this.pSubmodule = new SubmoduleElements();
		this.pEntity = new EntityElements();
		this.pQualifiedName = new QualifiedNameElements();
		this.pOperation = new OperationElements();
		this.pSubOperation = new SubOperationElements();
		this.pGeneralEntity = new GeneralEntityElements();
		this.pProperty = new PropertyElements();
		this.pType = new TypeElements();
		this.pSpecialEntity = new SpecialEntityElements();
		this.pTransaction = new TransactionElements();
		this.pSubTransaction = new SubTransactionElements();
		this.pOperateson = new OperatesonElements();
		this.pRelationDom = new RelationDomElements();
		this.pArchitecture = new ArchitectureElements();
		this.pComponent = new ComponentElements();
		this.pComponentName = new ComponentNameElements();
		this.pLayer = new LayerElements();
		this.pLayerName = new LayerNameElements();
		this.pLayerSegment = new LayerSegmentElements();
		this.pLayerSegmentName = new LayerSegmentNameElements();
		this.pLayerSegmentRelation = new LayerSegmentRelationElements();
		this.pSublayerSegment = new SublayerSegmentElements();
		this.pSublayerSegmentName = new SublayerSegmentNameElements();
		this.pRelationArch = new RelationArchElements();
		this.pTechnology = new TechnologyElements();
		this.pJavaApp = new JavaAppElements();
		this.pReactApp = new ReactAppElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.casino.dsl.Dsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	////---------------------- System ------------------------------------------------
	//System:
	//	'Casino' '{'
	//	dom=Domain
	//	arch=Architecture
	//	tech=Technology
	//	'}';
	public SystemElements getSystemAccess() {
		return pSystem;
	}
	
	public ParserRule getSystemRule() {
		return getSystemAccess().getRule();
	}
	
	//// --------------------- Domain ------------------------------------------------
	//Domain:
	//	'domain' '{'
	//	elements+=AbstractElement*
	//	modules+=Module+
	//	relations+=RelationDom+
	//	'}';
	public DomainElements getDomainAccess() {
		return pDomain;
	}
	
	public ParserRule getDomainRule() {
		return getDomainAccess().getRule();
	}
	
	//AbstractElement:
	//	SpecialEntity | GeneralEntity | Type;
	public AbstractElementElements getAbstractElementAccess() {
		return pAbstractElement;
	}
	
	public ParserRule getAbstractElementRule() {
		return getAbstractElementAccess().getRule();
	}
	
	//Module:
	//	'module' name=ID '{'
	//	submodules+=Submodule+
	//	'}';
	public ModuleElements getModuleAccess() {
		return pModule;
	}
	
	public ParserRule getModuleRule() {
		return getModuleAccess().getRule();
	}
	
	//Submodule:
	//	'submodule' name=ID '{'
	//	operations+=Operation+
	//	entities+=Entity+
	//	'}';
	public SubmoduleElements getSubmoduleAccess() {
		return pSubmodule;
	}
	
	public ParserRule getSubmoduleRule() {
		return getSubmoduleAccess().getRule();
	}
	
	//Entity:
	//	type=[QualifiedName];
	public EntityElements getEntityAccess() {
		return pEntity;
	}
	
	public ParserRule getEntityRule() {
		return getEntityAccess().getRule();
	}
	
	//QualifiedName:
	//	name=ID;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}
	
	//Operation:
	//	'op' '{'
	//	'type:' SubOperation
	//	'operates_on:' target+=Entity
	//	'}';
	public OperationElements getOperationAccess() {
		return pOperation;
	}
	
	public ParserRule getOperationRule() {
		return getOperationAccess().getRule();
	}
	
	//SubOperation:
	//	'Read' | 'Create';
	public SubOperationElements getSubOperationAccess() {
		return pSubOperation;
	}
	
	public ParserRule getSubOperationRule() {
		return getSubOperationAccess().getRule();
	}
	
	//GeneralEntity:
	//	'generalEntity' QualifiedName '{'
	//	properties+=Property+
	//	'}';
	public GeneralEntityElements getGeneralEntityAccess() {
		return pGeneralEntity;
	}
	
	public ParserRule getGeneralEntityRule() {
		return getGeneralEntityAccess().getRule();
	}
	
	//Property:
	//	name=ID ':' type=[Type];
	public PropertyElements getPropertyAccess() {
		return pProperty;
	}
	
	public ParserRule getPropertyRule() {
		return getPropertyAccess().getRule();
	}
	
	//Type:
	//	'dataType' name=ID;
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//SpecialEntity:
	//	'specialEntity' QualifiedName '{'
	//	properties+=Property+
	//	transactions+=Transaction+
	//	'}';
	public SpecialEntityElements getSpecialEntityAccess() {
		return pSpecialEntity;
	}
	
	public ParserRule getSpecialEntityRule() {
		return getSpecialEntityAccess().getRule();
	}
	
	//Transaction:
	//	'trx' '{'
	//	'type:' SubTransaction
	//	operateson+=Operateson+
	//	'}';
	public TransactionElements getTransactionAccess() {
		return pTransaction;
	}
	
	public ParserRule getTransactionRule() {
		return getTransactionAccess().getRule();
	}
	
	//SubTransaction:
	//	'exchange' | 'sale';
	public SubTransactionElements getSubTransactionAccess() {
		return pSubTransaction;
	}
	
	public ParserRule getSubTransactionRule() {
		return getSubTransactionAccess().getRule();
	}
	
	//Operateson:
	//	'operates_on:' type=[GeneralEntity];
	public OperatesonElements getOperatesonAccess() {
		return pOperateson;
	}
	
	public ParserRule getOperatesonRule() {
		return getOperatesonAccess().getRule();
	}
	
	//RelationDom:
	//	'rel' '{'
	//	'type:' 'Composition'
	//	'source:' type=[GeneralEntity]
	//	'target:' target+=Entity
	//	'}';
	public RelationDomElements getRelationDomAccess() {
		return pRelationDom;
	}
	
	public ParserRule getRelationDomRule() {
		return getRelationDomAccess().getRule();
	}
	
	//// --------------------- Architecture ----------------------------------------------
	//Architecture:
	//	'arch' '{'
	//	componentes+=Component+
	//	relationArch+=RelationArch+
	//	'}';
	public ArchitectureElements getArchitectureAccess() {
		return pArchitecture;
	}
	
	public ParserRule getArchitectureRule() {
		return getArchitectureAccess().getRule();
	}
	
	//Component:
	//	'component' ComponentName '{'
	//	layer+=Layer+
	//	'}';
	public ComponentElements getComponentAccess() {
		return pComponent;
	}
	
	public ParserRule getComponentRule() {
		return getComponentAccess().getRule();
	}
	
	//ComponentName:
	//	'Back' | 'Front';
	public ComponentNameElements getComponentNameAccess() {
		return pComponentName;
	}
	
	public ParserRule getComponentNameRule() {
		return getComponentNameAccess().getRule();
	}
	
	//Layer:
	//	'layer' name=LayerName '{'
	//	layerSegments+=LayerSegment*
	//	'}';
	public LayerElements getLayerAccess() {
		return pLayer;
	}
	
	public ParserRule getLayerRule() {
		return getLayerAccess().getRule();
	}
	
	//LayerName:
	//	'JavaScript' | 'Ejb' | 'War';
	public LayerNameElements getLayerNameAccess() {
		return pLayerName;
	}
	
	public ParserRule getLayerNameRule() {
		return getLayerNameAccess().getRule();
	}
	
	//LayerSegment:
	//	'layerSegment' name=LayerSegmentName '{' ('{' relations+=LayerSegmentRelation* '}')?
	//	sublayerSegments+=SublayerSegment*
	//	'}';
	public LayerSegmentElements getLayerSegmentAccess() {
		return pLayerSegment;
	}
	
	public ParserRule getLayerSegmentRule() {
		return getLayerSegmentAccess().getRule();
	}
	
	//LayerSegmentName:
	//	'Services' | 'Ui' | 'Store' | 'RestEntity' | 'Pojo' | 'Facade' | 'Dto' | 'Util' | 'Containers';
	public LayerSegmentNameElements getLayerSegmentNameAccess() {
		return pLayerSegmentName;
	}
	
	public ParserRule getLayerSegmentNameRule() {
		return getLayerSegmentNameAccess().getRule();
	}
	
	//LayerSegmentRelation:
	//	'allowedToUse:' LayerSegmentName;
	public LayerSegmentRelationElements getLayerSegmentRelationAccess() {
		return pLayerSegmentRelation;
	}
	
	public ParserRule getLayerSegmentRelationRule() {
		return getLayerSegmentRelationAccess().getRule();
	}
	
	//SublayerSegment:
	//	'sublayerSegment' name=SublayerSegmentName;
	public SublayerSegmentElements getSublayerSegmentAccess() {
		return pSublayerSegment;
	}
	
	public ParserRule getSublayerSegmentRule() {
		return getSublayerSegmentAccess().getRule();
	}
	
	//SublayerSegmentName:
	//	'Actions' | 'Reducers';
	public SublayerSegmentNameElements getSublayerSegmentNameAccess() {
		return pSublayerSegmentName;
	}
	
	public ParserRule getSublayerSegmentNameRule() {
		return getSublayerSegmentNameAccess().getRule();
	}
	
	//RelationArch:
	//	'relationArch' name=ID '{'
	//	'source:' LayerName ','
	//	'target:' LayerName
	//	'}';
	public RelationArchElements getRelationArchAccess() {
		return pRelationArch;
	}
	
	public ParserRule getRelationArchRule() {
		return getRelationArchAccess().getRule();
	}
	
	//// --------------------- Technology ------------------------------------------------
	//Technology:
	//	'tech' '{'
	//	java=JavaApp
	//	react=ReactApp
	//	'}';
	public TechnologyElements getTechnologyAccess() {
		return pTechnology;
	}
	
	public ParserRule getTechnologyRule() {
		return getTechnologyAccess().getRule();
	}
	
	//// --------------------- Backend----- ----------------------------------------------
	//JavaApp:
	//	'javaApp' '{'
	//	'}';
	public JavaAppElements getJavaAppAccess() {
		return pJavaApp;
	}
	
	public ParserRule getJavaAppRule() {
		return getJavaAppAccess().getRule();
	}
	
	//// --------------------- Frontend---- ----------------------------------------------
	//ReactApp:
	//	'reactApp' '{'
	//	'}';
	public ReactAppElements getReactAppAccess() {
		return pReactApp;
	}
	
	public ParserRule getReactAppRule() {
		return getReactAppAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
