/*
 * generated by Xtext 2.18.0
 */
package org.xtext.casino.dsl.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.casino.dsl.services.DslGrammarAccess;

@SuppressWarnings("all")
public class DslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected DslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_GeneralEntity_SpecialEntity_GeneralEntityKeyword_0_or_SpecialEntityKeyword_0;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (DslGrammarAccess) access;
		match_GeneralEntity_SpecialEntity_GeneralEntityKeyword_0_or_SpecialEntityKeyword_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getGeneralEntityAccess().getGeneralEntityKeyword_0()), new TokenAlias(false, false, grammarAccess.getSpecialEntityAccess().getSpecialEntityKeyword_0()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getSubOperationRule())
			return getSubOperationToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getSubTransactionRule())
			return getSubTransactionToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * SubOperation:
	 * 	'Read' | 'Create'
	 * ;
	 */
	protected String getSubOperationToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "Read";
	}
	
	/**
	 * SubTransaction:
	 * 	'exchange' | 'sale'
	 * ;
	 */
	protected String getSubTransactionToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "exchange";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_GeneralEntity_SpecialEntity_GeneralEntityKeyword_0_or_SpecialEntityKeyword_0.equals(syntax))
				emit_GeneralEntity_SpecialEntity_GeneralEntityKeyword_0_or_SpecialEntityKeyword_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'generalEntity' | 'specialEntity'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) name=ID
	 */
	protected void emit_GeneralEntity_SpecialEntity_GeneralEntityKeyword_0_or_SpecialEntityKeyword_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
