/**
 * generated by Xtext 2.17.0
 */
package org.xtext.casino.dsl.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.casino.dsl.dsl.Action#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.casino.dsl.dsl.Action#getActionCreator <em>Action Creator</em>}</li>
 *   <li>{@link org.xtext.casino.dsl.dsl.Action#getActionDispatcher <em>Action Dispatcher</em>}</li>
 *   <li>{@link org.xtext.casino.dsl.dsl.Action#getDir <em>Dir</em>}</li>
 * </ul>
 *
 * @see org.xtext.casino.dsl.dsl.DslPackage#getAction()
 * @model
 * @generated
 */
public interface Action extends AbstractFrontElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.casino.dsl.dsl.DslPackage#getAction_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.casino.dsl.dsl.Action#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Action Creator</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action Creator</em>' reference.
   * @see #setActionCreator(ActionCreator)
   * @see org.xtext.casino.dsl.dsl.DslPackage#getAction_ActionCreator()
   * @model
   * @generated
   */
  ActionCreator getActionCreator();

  /**
   * Sets the value of the '{@link org.xtext.casino.dsl.dsl.Action#getActionCreator <em>Action Creator</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action Creator</em>' reference.
   * @see #getActionCreator()
   * @generated
   */
  void setActionCreator(ActionCreator value);

  /**
   * Returns the value of the '<em><b>Action Dispatcher</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action Dispatcher</em>' reference.
   * @see #setActionDispatcher(ActionDispatcher)
   * @see org.xtext.casino.dsl.dsl.DslPackage#getAction_ActionDispatcher()
   * @model
   * @generated
   */
  ActionDispatcher getActionDispatcher();

  /**
   * Sets the value of the '{@link org.xtext.casino.dsl.dsl.Action#getActionDispatcher <em>Action Dispatcher</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action Dispatcher</em>' reference.
   * @see #getActionDispatcher()
   * @generated
   */
  void setActionDispatcher(ActionDispatcher value);

  /**
   * Returns the value of the '<em><b>Dir</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dir</em>' reference.
   * @see #setDir(Directory)
   * @see org.xtext.casino.dsl.dsl.DslPackage#getAction_Dir()
   * @model
   * @generated
   */
  Directory getDir();

  /**
   * Sets the value of the '{@link org.xtext.casino.dsl.dsl.Action#getDir <em>Dir</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dir</em>' reference.
   * @see #getDir()
   * @generated
   */
  void setDir(Directory value);

} // Action
