/**
 * generated by Xtext 2.17.0
 */
package org.xtext.casino.dsl.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Annotation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.casino.dsl.dsl.DslPackage#getAnnotation()
 * @model
 * @generated
 */
public interface Annotation extends Eclass
{
} // Annotation
