/**
 * generated by Xtext 2.18.0
 */
package org.xtext.casino.dsl.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Architecture</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.casino.dsl.dsl.Architecture#getComponentes <em>Componentes</em>}</li>
 *   <li>{@link org.xtext.casino.dsl.dsl.Architecture#getRelationArch <em>Relation Arch</em>}</li>
 * </ul>
 *
 * @see org.xtext.casino.dsl.dsl.DslPackage#getArchitecture()
 * @model
 * @generated
 */
public interface Architecture extends EObject
{
  /**
   * Returns the value of the '<em><b>Componentes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.casino.dsl.dsl.Component}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Componentes</em>' containment reference list.
   * @see org.xtext.casino.dsl.dsl.DslPackage#getArchitecture_Componentes()
   * @model containment="true"
   * @generated
   */
  EList<Component> getComponentes();

  /**
   * Returns the value of the '<em><b>Relation Arch</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.casino.dsl.dsl.RelationArch}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relation Arch</em>' containment reference list.
   * @see org.xtext.casino.dsl.dsl.DslPackage#getArchitecture_RelationArch()
   * @model containment="true"
   * @generated
   */
  EList<RelationArch> getRelationArch();

} // Architecture
