/**
 * generated by Xtext 2.18.0
 */
package org.xtext.casino.dsl.dsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.casino.dsl.dsl.DslFactory
 * @model kind="package"
 * @generated
 */
public interface DslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/casino/dsl/Dsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DslPackage eINSTANCE = org.xtext.casino.dsl.dsl.impl.DslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.casino.dsl.dsl.impl.SystemImpl <em>System</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.casino.dsl.dsl.impl.SystemImpl
   * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getSystem()
   * @generated
   */
  int SYSTEM = 0;

  /**
   * The feature id for the '<em><b>Dom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__DOM = 0;

  /**
   * The feature id for the '<em><b>Arch</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__ARCH = 1;

  /**
   * The feature id for the '<em><b>Tech</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__TECH = 2;

  /**
   * The number of structural features of the '<em>System</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.casino.dsl.dsl.impl.DomainImpl <em>Domain</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.casino.dsl.dsl.impl.DomainImpl
   * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getDomain()
   * @generated
   */
  int DOMAIN = 1;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN__ELEMENTS = 0;

  /**
   * The feature id for the '<em><b>Modules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN__MODULES = 1;

  /**
   * The feature id for the '<em><b>Relations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN__RELATIONS = 2;

  /**
   * The number of structural features of the '<em>Domain</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.casino.dsl.dsl.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.casino.dsl.dsl.impl.AbstractElementImpl
   * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getAbstractElement()
   * @generated
   */
  int ABSTRACT_ELEMENT = 2;

  /**
   * The number of structural features of the '<em>Abstract Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.casino.dsl.dsl.impl.ModuleImpl <em>Module</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.casino.dsl.dsl.impl.ModuleImpl
   * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getModule()
   * @generated
   */
  int MODULE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE__NAME = 0;

  /**
   * The feature id for the '<em><b>Submodules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE__SUBMODULES = 1;

  /**
   * The number of structural features of the '<em>Module</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.casino.dsl.dsl.impl.SubmoduleImpl <em>Submodule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.casino.dsl.dsl.impl.SubmoduleImpl
   * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getSubmodule()
   * @generated
   */
  int SUBMODULE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBMODULE__NAME = 0;

  /**
   * The feature id for the '<em><b>Operations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBMODULE__OPERATIONS = 1;

  /**
   * The feature id for the '<em><b>Entities</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBMODULE__ENTITIES = 2;

  /**
   * The number of structural features of the '<em>Submodule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBMODULE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.casino.dsl.dsl.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.casino.dsl.dsl.impl.EntityImpl
   * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 5;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__TYPE = 0;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.casino.dsl.dsl.impl.GeneralEntityImpl <em>General Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.casino.dsl.dsl.impl.GeneralEntityImpl
   * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getGeneralEntity()
   * @generated
   */
  int GENERAL_ENTITY = 8;

  /**
   * The number of structural features of the '<em>General Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_ENTITY_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.casino.dsl.dsl.impl.QualifiedNameImpl <em>Qualified Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.casino.dsl.dsl.impl.QualifiedNameImpl
   * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getQualifiedName()
   * @generated
   */
  int QUALIFIED_NAME = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUALIFIED_NAME__NAME = GENERAL_ENTITY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUALIFIED_NAME__PROPERTIES = GENERAL_ENTITY_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Transactions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUALIFIED_NAME__TRANSACTIONS = GENERAL_ENTITY_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Qualified Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUALIFIED_NAME_FEATURE_COUNT = GENERAL_ENTITY_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.casino.dsl.dsl.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.casino.dsl.dsl.impl.OperationImpl
   * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 7;

  /**
   * The feature id for the '<em><b>Target</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__TARGET = 0;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.casino.dsl.dsl.impl.PropertyImpl <em>Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.casino.dsl.dsl.impl.PropertyImpl
   * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getProperty()
   * @generated
   */
  int PROPERTY = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__TYPE = 1;

  /**
   * The number of structural features of the '<em>Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.casino.dsl.dsl.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.casino.dsl.dsl.impl.TypeImpl
   * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getType()
   * @generated
   */
  int TYPE = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.casino.dsl.dsl.impl.SpecialEntityImpl <em>Special Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.casino.dsl.dsl.impl.SpecialEntityImpl
   * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getSpecialEntity()
   * @generated
   */
  int SPECIAL_ENTITY = 11;

  /**
   * The number of structural features of the '<em>Special Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPECIAL_ENTITY_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.casino.dsl.dsl.impl.TransactionImpl <em>Transaction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.casino.dsl.dsl.impl.TransactionImpl
   * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getTransaction()
   * @generated
   */
  int TRANSACTION = 12;

  /**
   * The feature id for the '<em><b>Operateson</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSACTION__OPERATESON = 0;

  /**
   * The number of structural features of the '<em>Transaction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSACTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.casino.dsl.dsl.impl.OperatesonImpl <em>Operateson</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.casino.dsl.dsl.impl.OperatesonImpl
   * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getOperateson()
   * @generated
   */
  int OPERATESON = 13;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATESON__TYPE = 0;

  /**
   * The number of structural features of the '<em>Operateson</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATESON_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.casino.dsl.dsl.impl.RelationDomImpl <em>Relation Dom</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.casino.dsl.dsl.impl.RelationDomImpl
   * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getRelationDom()
   * @generated
   */
  int RELATION_DOM = 14;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_DOM__TYPE = 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_DOM__TARGET = 1;

  /**
   * The number of structural features of the '<em>Relation Dom</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_DOM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.casino.dsl.dsl.impl.ArchitectureImpl <em>Architecture</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.casino.dsl.dsl.impl.ArchitectureImpl
   * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getArchitecture()
   * @generated
   */
  int ARCHITECTURE = 15;

  /**
   * The feature id for the '<em><b>Componentes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHITECTURE__COMPONENTES = 0;

  /**
   * The feature id for the '<em><b>Relation Arch</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHITECTURE__RELATION_ARCH = 1;

  /**
   * The number of structural features of the '<em>Architecture</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHITECTURE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.casino.dsl.dsl.impl.ComponentImpl <em>Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.casino.dsl.dsl.impl.ComponentImpl
   * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getComponent()
   * @generated
   */
  int COMPONENT = 16;

  /**
   * The feature id for the '<em><b>Layer</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__LAYER = 0;

  /**
   * The number of structural features of the '<em>Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.casino.dsl.dsl.impl.LayerImpl <em>Layer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.casino.dsl.dsl.impl.LayerImpl
   * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getLayer()
   * @generated
   */
  int LAYER = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER__NAME = 0;

  /**
   * The feature id for the '<em><b>Layer Segments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER__LAYER_SEGMENTS = 1;

  /**
   * The number of structural features of the '<em>Layer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.casino.dsl.dsl.impl.LayerSegmentImpl <em>Layer Segment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.casino.dsl.dsl.impl.LayerSegmentImpl
   * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getLayerSegment()
   * @generated
   */
  int LAYER_SEGMENT = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER_SEGMENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Relations</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER_SEGMENT__RELATIONS = 1;

  /**
   * The feature id for the '<em><b>Sublayer Segments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER_SEGMENT__SUBLAYER_SEGMENTS = 2;

  /**
   * The number of structural features of the '<em>Layer Segment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER_SEGMENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.casino.dsl.dsl.impl.SublayerSegmentImpl <em>Sublayer Segment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.casino.dsl.dsl.impl.SublayerSegmentImpl
   * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getSublayerSegment()
   * @generated
   */
  int SUBLAYER_SEGMENT = 19;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBLAYER_SEGMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Sublayer Segment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBLAYER_SEGMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.casino.dsl.dsl.impl.RelationArchImpl <em>Relation Arch</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.casino.dsl.dsl.impl.RelationArchImpl
   * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getRelationArch()
   * @generated
   */
  int RELATION_ARCH = 20;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_ARCH__NAME = 0;

  /**
   * The number of structural features of the '<em>Relation Arch</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_ARCH_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.casino.dsl.dsl.impl.TechnologyImpl <em>Technology</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.casino.dsl.dsl.impl.TechnologyImpl
   * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getTechnology()
   * @generated
   */
  int TECHNOLOGY = 21;

  /**
   * The feature id for the '<em><b>Java</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TECHNOLOGY__JAVA = 0;

  /**
   * The feature id for the '<em><b>React</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TECHNOLOGY__REACT = 1;

  /**
   * The number of structural features of the '<em>Technology</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TECHNOLOGY_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.casino.dsl.dsl.System <em>System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System</em>'.
   * @see org.xtext.casino.dsl.dsl.System
   * @generated
   */
  EClass getSystem();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.casino.dsl.dsl.System#getDom <em>Dom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dom</em>'.
   * @see org.xtext.casino.dsl.dsl.System#getDom()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Dom();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.casino.dsl.dsl.System#getArch <em>Arch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Arch</em>'.
   * @see org.xtext.casino.dsl.dsl.System#getArch()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Arch();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.casino.dsl.dsl.System#getTech <em>Tech</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tech</em>'.
   * @see org.xtext.casino.dsl.dsl.System#getTech()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Tech();

  /**
   * Returns the meta object for class '{@link org.xtext.casino.dsl.dsl.Domain <em>Domain</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Domain</em>'.
   * @see org.xtext.casino.dsl.dsl.Domain
   * @generated
   */
  EClass getDomain();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.casino.dsl.dsl.Domain#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.casino.dsl.dsl.Domain#getElements()
   * @see #getDomain()
   * @generated
   */
  EReference getDomain_Elements();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.casino.dsl.dsl.Domain#getModules <em>Modules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Modules</em>'.
   * @see org.xtext.casino.dsl.dsl.Domain#getModules()
   * @see #getDomain()
   * @generated
   */
  EReference getDomain_Modules();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.casino.dsl.dsl.Domain#getRelations <em>Relations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Relations</em>'.
   * @see org.xtext.casino.dsl.dsl.Domain#getRelations()
   * @see #getDomain()
   * @generated
   */
  EReference getDomain_Relations();

  /**
   * Returns the meta object for class '{@link org.xtext.casino.dsl.dsl.AbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Element</em>'.
   * @see org.xtext.casino.dsl.dsl.AbstractElement
   * @generated
   */
  EClass getAbstractElement();

  /**
   * Returns the meta object for class '{@link org.xtext.casino.dsl.dsl.Module <em>Module</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Module</em>'.
   * @see org.xtext.casino.dsl.dsl.Module
   * @generated
   */
  EClass getModule();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.casino.dsl.dsl.Module#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.casino.dsl.dsl.Module#getName()
   * @see #getModule()
   * @generated
   */
  EAttribute getModule_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.casino.dsl.dsl.Module#getSubmodules <em>Submodules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Submodules</em>'.
   * @see org.xtext.casino.dsl.dsl.Module#getSubmodules()
   * @see #getModule()
   * @generated
   */
  EReference getModule_Submodules();

  /**
   * Returns the meta object for class '{@link org.xtext.casino.dsl.dsl.Submodule <em>Submodule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Submodule</em>'.
   * @see org.xtext.casino.dsl.dsl.Submodule
   * @generated
   */
  EClass getSubmodule();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.casino.dsl.dsl.Submodule#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.casino.dsl.dsl.Submodule#getName()
   * @see #getSubmodule()
   * @generated
   */
  EAttribute getSubmodule_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.casino.dsl.dsl.Submodule#getOperations <em>Operations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operations</em>'.
   * @see org.xtext.casino.dsl.dsl.Submodule#getOperations()
   * @see #getSubmodule()
   * @generated
   */
  EReference getSubmodule_Operations();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.casino.dsl.dsl.Submodule#getEntities <em>Entities</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entities</em>'.
   * @see org.xtext.casino.dsl.dsl.Submodule#getEntities()
   * @see #getSubmodule()
   * @generated
   */
  EReference getSubmodule_Entities();

  /**
   * Returns the meta object for class '{@link org.xtext.casino.dsl.dsl.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see org.xtext.casino.dsl.dsl.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for the reference '{@link org.xtext.casino.dsl.dsl.Entity#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.xtext.casino.dsl.dsl.Entity#getType()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.casino.dsl.dsl.QualifiedName <em>Qualified Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Qualified Name</em>'.
   * @see org.xtext.casino.dsl.dsl.QualifiedName
   * @generated
   */
  EClass getQualifiedName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.casino.dsl.dsl.QualifiedName#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.casino.dsl.dsl.QualifiedName#getName()
   * @see #getQualifiedName()
   * @generated
   */
  EAttribute getQualifiedName_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.casino.dsl.dsl.QualifiedName#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see org.xtext.casino.dsl.dsl.QualifiedName#getProperties()
   * @see #getQualifiedName()
   * @generated
   */
  EReference getQualifiedName_Properties();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.casino.dsl.dsl.QualifiedName#getTransactions <em>Transactions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Transactions</em>'.
   * @see org.xtext.casino.dsl.dsl.QualifiedName#getTransactions()
   * @see #getQualifiedName()
   * @generated
   */
  EReference getQualifiedName_Transactions();

  /**
   * Returns the meta object for class '{@link org.xtext.casino.dsl.dsl.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see org.xtext.casino.dsl.dsl.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.casino.dsl.dsl.Operation#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Target</em>'.
   * @see org.xtext.casino.dsl.dsl.Operation#getTarget()
   * @see #getOperation()
   * @generated
   */
  EReference getOperation_Target();

  /**
   * Returns the meta object for class '{@link org.xtext.casino.dsl.dsl.GeneralEntity <em>General Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>General Entity</em>'.
   * @see org.xtext.casino.dsl.dsl.GeneralEntity
   * @generated
   */
  EClass getGeneralEntity();

  /**
   * Returns the meta object for class '{@link org.xtext.casino.dsl.dsl.Property <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property</em>'.
   * @see org.xtext.casino.dsl.dsl.Property
   * @generated
   */
  EClass getProperty();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.casino.dsl.dsl.Property#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.casino.dsl.dsl.Property#getName()
   * @see #getProperty()
   * @generated
   */
  EAttribute getProperty_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.casino.dsl.dsl.Property#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.xtext.casino.dsl.dsl.Property#getType()
   * @see #getProperty()
   * @generated
   */
  EReference getProperty_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.casino.dsl.dsl.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.xtext.casino.dsl.dsl.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.casino.dsl.dsl.Type#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.casino.dsl.dsl.Type#getName()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.casino.dsl.dsl.SpecialEntity <em>Special Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Special Entity</em>'.
   * @see org.xtext.casino.dsl.dsl.SpecialEntity
   * @generated
   */
  EClass getSpecialEntity();

  /**
   * Returns the meta object for class '{@link org.xtext.casino.dsl.dsl.Transaction <em>Transaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transaction</em>'.
   * @see org.xtext.casino.dsl.dsl.Transaction
   * @generated
   */
  EClass getTransaction();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.casino.dsl.dsl.Transaction#getOperateson <em>Operateson</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Operateson</em>'.
   * @see org.xtext.casino.dsl.dsl.Transaction#getOperateson()
   * @see #getTransaction()
   * @generated
   */
  EReference getTransaction_Operateson();

  /**
   * Returns the meta object for class '{@link org.xtext.casino.dsl.dsl.Operateson <em>Operateson</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operateson</em>'.
   * @see org.xtext.casino.dsl.dsl.Operateson
   * @generated
   */
  EClass getOperateson();

  /**
   * Returns the meta object for the reference '{@link org.xtext.casino.dsl.dsl.Operateson#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.xtext.casino.dsl.dsl.Operateson#getType()
   * @see #getOperateson()
   * @generated
   */
  EReference getOperateson_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.casino.dsl.dsl.RelationDom <em>Relation Dom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relation Dom</em>'.
   * @see org.xtext.casino.dsl.dsl.RelationDom
   * @generated
   */
  EClass getRelationDom();

  /**
   * Returns the meta object for the reference '{@link org.xtext.casino.dsl.dsl.RelationDom#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.xtext.casino.dsl.dsl.RelationDom#getType()
   * @see #getRelationDom()
   * @generated
   */
  EReference getRelationDom_Type();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.casino.dsl.dsl.RelationDom#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Target</em>'.
   * @see org.xtext.casino.dsl.dsl.RelationDom#getTarget()
   * @see #getRelationDom()
   * @generated
   */
  EReference getRelationDom_Target();

  /**
   * Returns the meta object for class '{@link org.xtext.casino.dsl.dsl.Architecture <em>Architecture</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Architecture</em>'.
   * @see org.xtext.casino.dsl.dsl.Architecture
   * @generated
   */
  EClass getArchitecture();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.casino.dsl.dsl.Architecture#getComponentes <em>Componentes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Componentes</em>'.
   * @see org.xtext.casino.dsl.dsl.Architecture#getComponentes()
   * @see #getArchitecture()
   * @generated
   */
  EReference getArchitecture_Componentes();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.casino.dsl.dsl.Architecture#getRelationArch <em>Relation Arch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Relation Arch</em>'.
   * @see org.xtext.casino.dsl.dsl.Architecture#getRelationArch()
   * @see #getArchitecture()
   * @generated
   */
  EReference getArchitecture_RelationArch();

  /**
   * Returns the meta object for class '{@link org.xtext.casino.dsl.dsl.Component <em>Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component</em>'.
   * @see org.xtext.casino.dsl.dsl.Component
   * @generated
   */
  EClass getComponent();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.casino.dsl.dsl.Component#getLayer <em>Layer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Layer</em>'.
   * @see org.xtext.casino.dsl.dsl.Component#getLayer()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_Layer();

  /**
   * Returns the meta object for class '{@link org.xtext.casino.dsl.dsl.Layer <em>Layer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Layer</em>'.
   * @see org.xtext.casino.dsl.dsl.Layer
   * @generated
   */
  EClass getLayer();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.casino.dsl.dsl.Layer#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.casino.dsl.dsl.Layer#getName()
   * @see #getLayer()
   * @generated
   */
  EAttribute getLayer_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.casino.dsl.dsl.Layer#getLayerSegments <em>Layer Segments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Layer Segments</em>'.
   * @see org.xtext.casino.dsl.dsl.Layer#getLayerSegments()
   * @see #getLayer()
   * @generated
   */
  EReference getLayer_LayerSegments();

  /**
   * Returns the meta object for class '{@link org.xtext.casino.dsl.dsl.LayerSegment <em>Layer Segment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Layer Segment</em>'.
   * @see org.xtext.casino.dsl.dsl.LayerSegment
   * @generated
   */
  EClass getLayerSegment();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.casino.dsl.dsl.LayerSegment#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.casino.dsl.dsl.LayerSegment#getName()
   * @see #getLayerSegment()
   * @generated
   */
  EAttribute getLayerSegment_Name();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.casino.dsl.dsl.LayerSegment#getRelations <em>Relations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Relations</em>'.
   * @see org.xtext.casino.dsl.dsl.LayerSegment#getRelations()
   * @see #getLayerSegment()
   * @generated
   */
  EAttribute getLayerSegment_Relations();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.casino.dsl.dsl.LayerSegment#getSublayerSegments <em>Sublayer Segments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sublayer Segments</em>'.
   * @see org.xtext.casino.dsl.dsl.LayerSegment#getSublayerSegments()
   * @see #getLayerSegment()
   * @generated
   */
  EReference getLayerSegment_SublayerSegments();

  /**
   * Returns the meta object for class '{@link org.xtext.casino.dsl.dsl.SublayerSegment <em>Sublayer Segment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sublayer Segment</em>'.
   * @see org.xtext.casino.dsl.dsl.SublayerSegment
   * @generated
   */
  EClass getSublayerSegment();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.casino.dsl.dsl.SublayerSegment#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.casino.dsl.dsl.SublayerSegment#getName()
   * @see #getSublayerSegment()
   * @generated
   */
  EAttribute getSublayerSegment_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.casino.dsl.dsl.RelationArch <em>Relation Arch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relation Arch</em>'.
   * @see org.xtext.casino.dsl.dsl.RelationArch
   * @generated
   */
  EClass getRelationArch();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.casino.dsl.dsl.RelationArch#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.casino.dsl.dsl.RelationArch#getName()
   * @see #getRelationArch()
   * @generated
   */
  EAttribute getRelationArch_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.casino.dsl.dsl.Technology <em>Technology</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Technology</em>'.
   * @see org.xtext.casino.dsl.dsl.Technology
   * @generated
   */
  EClass getTechnology();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.casino.dsl.dsl.Technology#getJava <em>Java</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Java</em>'.
   * @see org.xtext.casino.dsl.dsl.Technology#getJava()
   * @see #getTechnology()
   * @generated
   */
  EAttribute getTechnology_Java();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.casino.dsl.dsl.Technology#getReact <em>React</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>React</em>'.
   * @see org.xtext.casino.dsl.dsl.Technology#getReact()
   * @see #getTechnology()
   * @generated
   */
  EAttribute getTechnology_React();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DslFactory getDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.casino.dsl.dsl.impl.SystemImpl <em>System</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.casino.dsl.dsl.impl.SystemImpl
     * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getSystem()
     * @generated
     */
    EClass SYSTEM = eINSTANCE.getSystem();

    /**
     * The meta object literal for the '<em><b>Dom</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__DOM = eINSTANCE.getSystem_Dom();

    /**
     * The meta object literal for the '<em><b>Arch</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__ARCH = eINSTANCE.getSystem_Arch();

    /**
     * The meta object literal for the '<em><b>Tech</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__TECH = eINSTANCE.getSystem_Tech();

    /**
     * The meta object literal for the '{@link org.xtext.casino.dsl.dsl.impl.DomainImpl <em>Domain</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.casino.dsl.dsl.impl.DomainImpl
     * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getDomain()
     * @generated
     */
    EClass DOMAIN = eINSTANCE.getDomain();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMAIN__ELEMENTS = eINSTANCE.getDomain_Elements();

    /**
     * The meta object literal for the '<em><b>Modules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMAIN__MODULES = eINSTANCE.getDomain_Modules();

    /**
     * The meta object literal for the '<em><b>Relations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMAIN__RELATIONS = eINSTANCE.getDomain_Relations();

    /**
     * The meta object literal for the '{@link org.xtext.casino.dsl.dsl.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.casino.dsl.dsl.impl.AbstractElementImpl
     * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getAbstractElement()
     * @generated
     */
    EClass ABSTRACT_ELEMENT = eINSTANCE.getAbstractElement();

    /**
     * The meta object literal for the '{@link org.xtext.casino.dsl.dsl.impl.ModuleImpl <em>Module</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.casino.dsl.dsl.impl.ModuleImpl
     * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getModule()
     * @generated
     */
    EClass MODULE = eINSTANCE.getModule();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODULE__NAME = eINSTANCE.getModule_Name();

    /**
     * The meta object literal for the '<em><b>Submodules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODULE__SUBMODULES = eINSTANCE.getModule_Submodules();

    /**
     * The meta object literal for the '{@link org.xtext.casino.dsl.dsl.impl.SubmoduleImpl <em>Submodule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.casino.dsl.dsl.impl.SubmoduleImpl
     * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getSubmodule()
     * @generated
     */
    EClass SUBMODULE = eINSTANCE.getSubmodule();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUBMODULE__NAME = eINSTANCE.getSubmodule_Name();

    /**
     * The meta object literal for the '<em><b>Operations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUBMODULE__OPERATIONS = eINSTANCE.getSubmodule_Operations();

    /**
     * The meta object literal for the '<em><b>Entities</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUBMODULE__ENTITIES = eINSTANCE.getSubmodule_Entities();

    /**
     * The meta object literal for the '{@link org.xtext.casino.dsl.dsl.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.casino.dsl.dsl.impl.EntityImpl
     * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__TYPE = eINSTANCE.getEntity_Type();

    /**
     * The meta object literal for the '{@link org.xtext.casino.dsl.dsl.impl.QualifiedNameImpl <em>Qualified Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.casino.dsl.dsl.impl.QualifiedNameImpl
     * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getQualifiedName()
     * @generated
     */
    EClass QUALIFIED_NAME = eINSTANCE.getQualifiedName();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUALIFIED_NAME__NAME = eINSTANCE.getQualifiedName_Name();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUALIFIED_NAME__PROPERTIES = eINSTANCE.getQualifiedName_Properties();

    /**
     * The meta object literal for the '<em><b>Transactions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUALIFIED_NAME__TRANSACTIONS = eINSTANCE.getQualifiedName_Transactions();

    /**
     * The meta object literal for the '{@link org.xtext.casino.dsl.dsl.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.casino.dsl.dsl.impl.OperationImpl
     * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION__TARGET = eINSTANCE.getOperation_Target();

    /**
     * The meta object literal for the '{@link org.xtext.casino.dsl.dsl.impl.GeneralEntityImpl <em>General Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.casino.dsl.dsl.impl.GeneralEntityImpl
     * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getGeneralEntity()
     * @generated
     */
    EClass GENERAL_ENTITY = eINSTANCE.getGeneralEntity();

    /**
     * The meta object literal for the '{@link org.xtext.casino.dsl.dsl.impl.PropertyImpl <em>Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.casino.dsl.dsl.impl.PropertyImpl
     * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getProperty()
     * @generated
     */
    EClass PROPERTY = eINSTANCE.getProperty();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY__NAME = eINSTANCE.getProperty_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY__TYPE = eINSTANCE.getProperty_Type();

    /**
     * The meta object literal for the '{@link org.xtext.casino.dsl.dsl.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.casino.dsl.dsl.impl.TypeImpl
     * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__NAME = eINSTANCE.getType_Name();

    /**
     * The meta object literal for the '{@link org.xtext.casino.dsl.dsl.impl.SpecialEntityImpl <em>Special Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.casino.dsl.dsl.impl.SpecialEntityImpl
     * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getSpecialEntity()
     * @generated
     */
    EClass SPECIAL_ENTITY = eINSTANCE.getSpecialEntity();

    /**
     * The meta object literal for the '{@link org.xtext.casino.dsl.dsl.impl.TransactionImpl <em>Transaction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.casino.dsl.dsl.impl.TransactionImpl
     * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getTransaction()
     * @generated
     */
    EClass TRANSACTION = eINSTANCE.getTransaction();

    /**
     * The meta object literal for the '<em><b>Operateson</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSACTION__OPERATESON = eINSTANCE.getTransaction_Operateson();

    /**
     * The meta object literal for the '{@link org.xtext.casino.dsl.dsl.impl.OperatesonImpl <em>Operateson</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.casino.dsl.dsl.impl.OperatesonImpl
     * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getOperateson()
     * @generated
     */
    EClass OPERATESON = eINSTANCE.getOperateson();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATESON__TYPE = eINSTANCE.getOperateson_Type();

    /**
     * The meta object literal for the '{@link org.xtext.casino.dsl.dsl.impl.RelationDomImpl <em>Relation Dom</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.casino.dsl.dsl.impl.RelationDomImpl
     * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getRelationDom()
     * @generated
     */
    EClass RELATION_DOM = eINSTANCE.getRelationDom();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION_DOM__TYPE = eINSTANCE.getRelationDom_Type();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION_DOM__TARGET = eINSTANCE.getRelationDom_Target();

    /**
     * The meta object literal for the '{@link org.xtext.casino.dsl.dsl.impl.ArchitectureImpl <em>Architecture</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.casino.dsl.dsl.impl.ArchitectureImpl
     * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getArchitecture()
     * @generated
     */
    EClass ARCHITECTURE = eINSTANCE.getArchitecture();

    /**
     * The meta object literal for the '<em><b>Componentes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARCHITECTURE__COMPONENTES = eINSTANCE.getArchitecture_Componentes();

    /**
     * The meta object literal for the '<em><b>Relation Arch</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARCHITECTURE__RELATION_ARCH = eINSTANCE.getArchitecture_RelationArch();

    /**
     * The meta object literal for the '{@link org.xtext.casino.dsl.dsl.impl.ComponentImpl <em>Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.casino.dsl.dsl.impl.ComponentImpl
     * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getComponent()
     * @generated
     */
    EClass COMPONENT = eINSTANCE.getComponent();

    /**
     * The meta object literal for the '<em><b>Layer</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__LAYER = eINSTANCE.getComponent_Layer();

    /**
     * The meta object literal for the '{@link org.xtext.casino.dsl.dsl.impl.LayerImpl <em>Layer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.casino.dsl.dsl.impl.LayerImpl
     * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getLayer()
     * @generated
     */
    EClass LAYER = eINSTANCE.getLayer();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LAYER__NAME = eINSTANCE.getLayer_Name();

    /**
     * The meta object literal for the '<em><b>Layer Segments</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAYER__LAYER_SEGMENTS = eINSTANCE.getLayer_LayerSegments();

    /**
     * The meta object literal for the '{@link org.xtext.casino.dsl.dsl.impl.LayerSegmentImpl <em>Layer Segment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.casino.dsl.dsl.impl.LayerSegmentImpl
     * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getLayerSegment()
     * @generated
     */
    EClass LAYER_SEGMENT = eINSTANCE.getLayerSegment();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LAYER_SEGMENT__NAME = eINSTANCE.getLayerSegment_Name();

    /**
     * The meta object literal for the '<em><b>Relations</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LAYER_SEGMENT__RELATIONS = eINSTANCE.getLayerSegment_Relations();

    /**
     * The meta object literal for the '<em><b>Sublayer Segments</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAYER_SEGMENT__SUBLAYER_SEGMENTS = eINSTANCE.getLayerSegment_SublayerSegments();

    /**
     * The meta object literal for the '{@link org.xtext.casino.dsl.dsl.impl.SublayerSegmentImpl <em>Sublayer Segment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.casino.dsl.dsl.impl.SublayerSegmentImpl
     * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getSublayerSegment()
     * @generated
     */
    EClass SUBLAYER_SEGMENT = eINSTANCE.getSublayerSegment();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUBLAYER_SEGMENT__NAME = eINSTANCE.getSublayerSegment_Name();

    /**
     * The meta object literal for the '{@link org.xtext.casino.dsl.dsl.impl.RelationArchImpl <em>Relation Arch</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.casino.dsl.dsl.impl.RelationArchImpl
     * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getRelationArch()
     * @generated
     */
    EClass RELATION_ARCH = eINSTANCE.getRelationArch();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATION_ARCH__NAME = eINSTANCE.getRelationArch_Name();

    /**
     * The meta object literal for the '{@link org.xtext.casino.dsl.dsl.impl.TechnologyImpl <em>Technology</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.casino.dsl.dsl.impl.TechnologyImpl
     * @see org.xtext.casino.dsl.dsl.impl.DslPackageImpl#getTechnology()
     * @generated
     */
    EClass TECHNOLOGY = eINSTANCE.getTechnology();

    /**
     * The meta object literal for the '<em><b>Java</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TECHNOLOGY__JAVA = eINSTANCE.getTechnology_Java();

    /**
     * The meta object literal for the '<em><b>React</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TECHNOLOGY__REACT = eINSTANCE.getTechnology_React();

  }

} //DslPackage
