/**
 * generated by Xtext 2.18.0
 */
package org.xtext.casino.dsl.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Special Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.casino.dsl.dsl.DslPackage#getSpecialEntity()
 * @model
 * @generated
 */
public interface SpecialEntity extends EObject
{
} // SpecialEntity
