/**
 * generated by Xtext 2.18.0
 */
package org.xtext.casino.dsl.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.casino.dsl.dsl.System#getDom <em>Dom</em>}</li>
 *   <li>{@link org.xtext.casino.dsl.dsl.System#getArch <em>Arch</em>}</li>
 *   <li>{@link org.xtext.casino.dsl.dsl.System#getTech <em>Tech</em>}</li>
 * </ul>
 *
 * @see org.xtext.casino.dsl.dsl.DslPackage#getSystem()
 * @model
 * @generated
 */
public interface System extends EObject
{
  /**
   * Returns the value of the '<em><b>Dom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dom</em>' containment reference.
   * @see #setDom(Domain)
   * @see org.xtext.casino.dsl.dsl.DslPackage#getSystem_Dom()
   * @model containment="true"
   * @generated
   */
  Domain getDom();

  /**
   * Sets the value of the '{@link org.xtext.casino.dsl.dsl.System#getDom <em>Dom</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dom</em>' containment reference.
   * @see #getDom()
   * @generated
   */
  void setDom(Domain value);

  /**
   * Returns the value of the '<em><b>Arch</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arch</em>' containment reference.
   * @see #setArch(Architecture)
   * @see org.xtext.casino.dsl.dsl.DslPackage#getSystem_Arch()
   * @model containment="true"
   * @generated
   */
  Architecture getArch();

  /**
   * Sets the value of the '{@link org.xtext.casino.dsl.dsl.System#getArch <em>Arch</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arch</em>' containment reference.
   * @see #getArch()
   * @generated
   */
  void setArch(Architecture value);

  /**
   * Returns the value of the '<em><b>Tech</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tech</em>' containment reference.
   * @see #setTech(Technology)
   * @see org.xtext.casino.dsl.dsl.DslPackage#getSystem_Tech()
   * @model containment="true"
   * @generated
   */
  Technology getTech();

  /**
   * Sets the value of the '{@link org.xtext.casino.dsl.dsl.System#getTech <em>Tech</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tech</em>' containment reference.
   * @see #getTech()
   * @generated
   */
  void setTech(Technology value);

} // System
