/**
 * generated by Xtext 2.18.0
 */
package org.xtext.casino.dsl.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Technology</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.casino.dsl.dsl.Technology#getJava <em>Java</em>}</li>
 *   <li>{@link org.xtext.casino.dsl.dsl.Technology#getReact <em>React</em>}</li>
 * </ul>
 *
 * @see org.xtext.casino.dsl.dsl.DslPackage#getTechnology()
 * @model
 * @generated
 */
public interface Technology extends EObject
{
  /**
   * Returns the value of the '<em><b>Java</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Java</em>' attribute.
   * @see #setJava(String)
   * @see org.xtext.casino.dsl.dsl.DslPackage#getTechnology_Java()
   * @model
   * @generated
   */
  String getJava();

  /**
   * Sets the value of the '{@link org.xtext.casino.dsl.dsl.Technology#getJava <em>Java</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Java</em>' attribute.
   * @see #getJava()
   * @generated
   */
  void setJava(String value);

  /**
   * Returns the value of the '<em><b>React</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>React</em>' attribute.
   * @see #setReact(String)
   * @see org.xtext.casino.dsl.dsl.DslPackage#getTechnology_React()
   * @model
   * @generated
   */
  String getReact();

  /**
   * Sets the value of the '{@link org.xtext.casino.dsl.dsl.Technology#getReact <em>React</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>React</em>' attribute.
   * @see #getReact()
   * @generated
   */
  void setReact(String value);

} // Technology
