/**
 * generated by Xtext 2.17.0
 */
package org.xtext.casino.dsl.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>UI Component</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.casino.dsl.dsl.DslPackage#getUIComponent()
 * @model
 * @generated
 */
public interface UIComponent extends EObject
{
} // UIComponent
