/**
 * generated by Xtext 2.17.0
 */
package org.xtext.casino.dsl.dsl.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.casino.dsl.dsl.AbstractClass;
import org.xtext.casino.dsl.dsl.AbstractFrontElement;
import org.xtext.casino.dsl.dsl.AbstractMethod;
import org.xtext.casino.dsl.dsl.Action;
import org.xtext.casino.dsl.dsl.ActionCreator;
import org.xtext.casino.dsl.dsl.ActionDispatcher;
import org.xtext.casino.dsl.dsl.Annotation;
import org.xtext.casino.dsl.dsl.Architecture;
import org.xtext.casino.dsl.dsl.Attribute;
import org.xtext.casino.dsl.dsl.Component;
import org.xtext.casino.dsl.dsl.Css;
import org.xtext.casino.dsl.dsl.Descriptor;
import org.xtext.casino.dsl.dsl.Directory;
import org.xtext.casino.dsl.dsl.Domain;
import org.xtext.casino.dsl.dsl.DslFactory;
import org.xtext.casino.dsl.dsl.DslPackage;
import org.xtext.casino.dsl.dsl.Eclass;
import org.xtext.casino.dsl.dsl.Einterface;
import org.xtext.casino.dsl.dsl.EntityName;
import org.xtext.casino.dsl.dsl.Epackage;
import org.xtext.casino.dsl.dsl.File;
import org.xtext.casino.dsl.dsl.Functionality;
import org.xtext.casino.dsl.dsl.GeneralEntity;
import org.xtext.casino.dsl.dsl.GenericClass;
import org.xtext.casino.dsl.dsl.JavaApp;
import org.xtext.casino.dsl.dsl.JeeProject;
import org.xtext.casino.dsl.dsl.Js;
import org.xtext.casino.dsl.dsl.JsModule;
import org.xtext.casino.dsl.dsl.Json;
import org.xtext.casino.dsl.dsl.Layer;
import org.xtext.casino.dsl.dsl.LayerSegment;
import org.xtext.casino.dsl.dsl.Library;
import org.xtext.casino.dsl.dsl.Md;
import org.xtext.casino.dsl.dsl.MethodBack;
import org.xtext.casino.dsl.dsl.NativeClass;
import org.xtext.casino.dsl.dsl.Operateson;
import org.xtext.casino.dsl.dsl.Operation;
import org.xtext.casino.dsl.dsl.Property;
import org.xtext.casino.dsl.dsl.ReactApp;
import org.xtext.casino.dsl.dsl.Reducer;
import org.xtext.casino.dsl.dsl.RelationArch;
import org.xtext.casino.dsl.dsl.RelationDom;
import org.xtext.casino.dsl.dsl.RouterComponent;
import org.xtext.casino.dsl.dsl.ServiceFront;
import org.xtext.casino.dsl.dsl.SpecialEntity;
import org.xtext.casino.dsl.dsl.State;
import org.xtext.casino.dsl.dsl.SublayerSegment;
import org.xtext.casino.dsl.dsl.Submodule;
import org.xtext.casino.dsl.dsl.Subproject;
import org.xtext.casino.dsl.dsl.Technology;
import org.xtext.casino.dsl.dsl.Transaction;
import org.xtext.casino.dsl.dsl.Type;
import org.xtext.casino.dsl.dsl.UIComponent;
import org.xtext.casino.dsl.dsl.Visualizer;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class DslFactoryImpl extends EFactoryImpl implements DslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static DslFactory init()
  {
    try
    {
      DslFactory theDslFactory = (DslFactory)EPackage.Registry.INSTANCE.getEFactory(DslPackage.eNS_URI);
      if (theDslFactory != null)
      {
        return theDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new DslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case DslPackage.SYSTEM: return createSystem();
      case DslPackage.DOMAIN: return createDomain();
      case DslPackage.MODULE: return createModule();
      case DslPackage.SUBMODULE: return createSubmodule();
      case DslPackage.OPERATION: return createOperation();
      case DslPackage.ENTITY_NAME: return createEntityName();
      case DslPackage.GENERAL_ENTITY: return createGeneralEntity();
      case DslPackage.PROPERTY: return createProperty();
      case DslPackage.TYPE: return createType();
      case DslPackage.SPECIAL_ENTITY: return createSpecialEntity();
      case DslPackage.TRANSACTION: return createTransaction();
      case DslPackage.OPERATESON: return createOperateson();
      case DslPackage.RELATION_DOM: return createRelationDom();
      case DslPackage.ARCHITECTURE: return createArchitecture();
      case DslPackage.COMPONENT: return createComponent();
      case DslPackage.LAYER: return createLayer();
      case DslPackage.LAYER_SEGMENT: return createLayerSegment();
      case DslPackage.SUBLAYER_SEGMENT: return createSublayerSegment();
      case DslPackage.RELATION_ARCH: return createRelationArch();
      case DslPackage.TECHNOLOGY: return createTechnology();
      case DslPackage.JAVA_APP: return createJavaApp();
      case DslPackage.JEE_PROJECT: return createJeeProject();
      case DslPackage.SUBPROJECT: return createSubproject();
      case DslPackage.ABSTRACT_CLASS: return createAbstractClass();
      case DslPackage.GENERIC_CLASS: return createGenericClass();
      case DslPackage.EINTERFACE: return createEinterface();
      case DslPackage.NATIVE_CLASS: return createNativeClass();
      case DslPackage.ECLASS: return createEclass();
      case DslPackage.ATTRIBUTE: return createAttribute();
      case DslPackage.EPACKAGE: return createEpackage();
      case DslPackage.METHOD_BACK: return createMethodBack();
      case DslPackage.ABSTRACT_METHOD: return createAbstractMethod();
      case DslPackage.DESCRIPTOR: return createDescriptor();
      case DslPackage.ANNOTATION: return createAnnotation();
      case DslPackage.LIBRARY: return createLibrary();
      case DslPackage.ABSTRACT_FRONT_ELEMENT: return createAbstractFrontElement();
      case DslPackage.REACT_APP: return createReactApp();
      case DslPackage.FUNCTIONALITY: return createFunctionality();
      case DslPackage.ROUTER_COMPONENT: return createRouterComponent();
      case DslPackage.UI_COMPONENT: return createUIComponent();
      case DslPackage.CONTAINER: return createContainer();
      case DslPackage.VISUALIZER: return createVisualizer();
      case DslPackage.SERVICE_FRONT: return createServiceFront();
      case DslPackage.DIRECTORY: return createDirectory();
      case DslPackage.FILE: return createFile();
      case DslPackage.MD: return createMd();
      case DslPackage.JS: return createJs();
      case DslPackage.JSON: return createJson();
      case DslPackage.CSS: return createCss();
      case DslPackage.STATE: return createState();
      case DslPackage.ACTION: return createAction();
      case DslPackage.ACTION_CREATOR: return createActionCreator();
      case DslPackage.ACTION_DISPATCHER: return createActionDispatcher();
      case DslPackage.REDUCER: return createReducer();
      case DslPackage.JS_MODULE: return createJsModule();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public org.xtext.casino.dsl.dsl.System createSystem()
  {
    SystemImpl system = new SystemImpl();
    return system;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Domain createDomain()
  {
    DomainImpl domain = new DomainImpl();
    return domain;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public org.xtext.casino.dsl.dsl.Module createModule()
  {
    ModuleImpl module = new ModuleImpl();
    return module;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Submodule createSubmodule()
  {
    SubmoduleImpl submodule = new SubmoduleImpl();
    return submodule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Operation createOperation()
  {
    OperationImpl operation = new OperationImpl();
    return operation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EntityName createEntityName()
  {
    EntityNameImpl entityName = new EntityNameImpl();
    return entityName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GeneralEntity createGeneralEntity()
  {
    GeneralEntityImpl generalEntity = new GeneralEntityImpl();
    return generalEntity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Property createProperty()
  {
    PropertyImpl property = new PropertyImpl();
    return property;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Type createType()
  {
    TypeImpl type = new TypeImpl();
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SpecialEntity createSpecialEntity()
  {
    SpecialEntityImpl specialEntity = new SpecialEntityImpl();
    return specialEntity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Transaction createTransaction()
  {
    TransactionImpl transaction = new TransactionImpl();
    return transaction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Operateson createOperateson()
  {
    OperatesonImpl operateson = new OperatesonImpl();
    return operateson;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RelationDom createRelationDom()
  {
    RelationDomImpl relationDom = new RelationDomImpl();
    return relationDom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Architecture createArchitecture()
  {
    ArchitectureImpl architecture = new ArchitectureImpl();
    return architecture;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Component createComponent()
  {
    ComponentImpl component = new ComponentImpl();
    return component;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Layer createLayer()
  {
    LayerImpl layer = new LayerImpl();
    return layer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LayerSegment createLayerSegment()
  {
    LayerSegmentImpl layerSegment = new LayerSegmentImpl();
    return layerSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SublayerSegment createSublayerSegment()
  {
    SublayerSegmentImpl sublayerSegment = new SublayerSegmentImpl();
    return sublayerSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RelationArch createRelationArch()
  {
    RelationArchImpl relationArch = new RelationArchImpl();
    return relationArch;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Technology createTechnology()
  {
    TechnologyImpl technology = new TechnologyImpl();
    return technology;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JavaApp createJavaApp()
  {
    JavaAppImpl javaApp = new JavaAppImpl();
    return javaApp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JeeProject createJeeProject()
  {
    JeeProjectImpl jeeProject = new JeeProjectImpl();
    return jeeProject;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Subproject createSubproject()
  {
    SubprojectImpl subproject = new SubprojectImpl();
    return subproject;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AbstractClass createAbstractClass()
  {
    AbstractClassImpl abstractClass = new AbstractClassImpl();
    return abstractClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GenericClass createGenericClass()
  {
    GenericClassImpl genericClass = new GenericClassImpl();
    return genericClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Einterface createEinterface()
  {
    EinterfaceImpl einterface = new EinterfaceImpl();
    return einterface;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NativeClass createNativeClass()
  {
    NativeClassImpl nativeClass = new NativeClassImpl();
    return nativeClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Eclass createEclass()
  {
    EclassImpl eclass = new EclassImpl();
    return eclass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Attribute createAttribute()
  {
    AttributeImpl attribute = new AttributeImpl();
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Epackage createEpackage()
  {
    EpackageImpl epackage = new EpackageImpl();
    return epackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MethodBack createMethodBack()
  {
    MethodBackImpl methodBack = new MethodBackImpl();
    return methodBack;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AbstractMethod createAbstractMethod()
  {
    AbstractMethodImpl abstractMethod = new AbstractMethodImpl();
    return abstractMethod;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Descriptor createDescriptor()
  {
    DescriptorImpl descriptor = new DescriptorImpl();
    return descriptor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Annotation createAnnotation()
  {
    AnnotationImpl annotation = new AnnotationImpl();
    return annotation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Library createLibrary()
  {
    LibraryImpl library = new LibraryImpl();
    return library;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AbstractFrontElement createAbstractFrontElement()
  {
    AbstractFrontElementImpl abstractFrontElement = new AbstractFrontElementImpl();
    return abstractFrontElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ReactApp createReactApp()
  {
    ReactAppImpl reactApp = new ReactAppImpl();
    return reactApp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Functionality createFunctionality()
  {
    FunctionalityImpl functionality = new FunctionalityImpl();
    return functionality;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RouterComponent createRouterComponent()
  {
    RouterComponentImpl routerComponent = new RouterComponentImpl();
    return routerComponent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UIComponent createUIComponent()
  {
    UIComponentImpl uiComponent = new UIComponentImpl();
    return uiComponent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public org.xtext.casino.dsl.dsl.Container createContainer()
  {
    ContainerImpl container = new ContainerImpl();
    return container;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Visualizer createVisualizer()
  {
    VisualizerImpl visualizer = new VisualizerImpl();
    return visualizer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ServiceFront createServiceFront()
  {
    ServiceFrontImpl serviceFront = new ServiceFrontImpl();
    return serviceFront;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Directory createDirectory()
  {
    DirectoryImpl directory = new DirectoryImpl();
    return directory;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public File createFile()
  {
    FileImpl file = new FileImpl();
    return file;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Md createMd()
  {
    MdImpl md = new MdImpl();
    return md;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Js createJs()
  {
    JsImpl js = new JsImpl();
    return js;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Json createJson()
  {
    JsonImpl json = new JsonImpl();
    return json;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Css createCss()
  {
    CssImpl css = new CssImpl();
    return css;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public State createState()
  {
    StateImpl state = new StateImpl();
    return state;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Action createAction()
  {
    ActionImpl action = new ActionImpl();
    return action;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ActionCreator createActionCreator()
  {
    ActionCreatorImpl actionCreator = new ActionCreatorImpl();
    return actionCreator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ActionDispatcher createActionDispatcher()
  {
    ActionDispatcherImpl actionDispatcher = new ActionDispatcherImpl();
    return actionDispatcher;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Reducer createReducer()
  {
    ReducerImpl reducer = new ReducerImpl();
    return reducer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public JsModule createJsModule()
  {
    JsModuleImpl jsModule = new JsModuleImpl();
    return jsModule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DslPackage getDslPackage()
  {
    return (DslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static DslPackage getPackage()
  {
    return DslPackage.eINSTANCE;
  }

} //DslFactoryImpl
