/**
 * generated by Xtext 2.18.0
 */
package org.xtext.casino.dsl.dsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.casino.dsl.dsl.DslPackage;
import org.xtext.casino.dsl.dsl.SpecialEntity;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Special Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SpecialEntityImpl extends MinimalEObjectImpl.Container implements SpecialEntity
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SpecialEntityImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.Literals.SPECIAL_ENTITY;
  }

} //SpecialEntityImpl
